export const LOGIN = "LOGIN"
export const INIT_USERID = "INIT_USERID"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const NOTICE_LIST = "NOTICE_LIST"
export const NOTICE_DEFAULT = "NOTICE_DEFAULT"
export const NOTICE_DETAIL = "NOTICE_DETAIL"
export const NOTICE_DETAIL_FAILURE = "NOTICE_DETAIL_FAILURE"

export const COURSE_HOT = "COUTSE_HOT"
export const COURSE_ALL = "COURSE_ALL"
export const COURSE_MY = "COURSE_MY"
export const COURSE_MY_ALL = "COURSE_MY_ALL"
export const COURSE_FAILURE = "COURSE_FAILURE"

export const COMMENT_DEFAULT = "COMMENT_DEFAULT"
export const COMMENT_PUBLISH = "COMMENT_PUBLISH"
export const COMMENT_PUBLISH_SUCCESS = "COMMENT_PUBLISH_SUCCESS"
export const COMMENT_PUBLISH_FAILURE = "COMMENT_PUBLISH_FAILURE"
